name: Backend Docker Build and Push
run-name: ${{ github.actor }} is backend docker build and push
on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # https://docs.github.com/en/actions/using-workflows/about-workflows
      - name: Checkout code
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/docker-login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./todo-app-be  # Path to the directory containing the Backend Dockerfile
          push: true
          tags: primesh96/todo-be:latest  # Customize the image tag/name as needed
